default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_lv1_development

test:
  <<: *default
  database: rails_lv1_test

production:
  <<: *default
  database: rails_lv1_production
